/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 chatgpt.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ChatGPT(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/model/chatgpt.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play the "FaceAction" animation every time the component is rendered
    if (actions.FaceAction) {
      actions.FaceAction.reset().fadeIn(0.5).play();
    }

    if (actions.Arm_1Action) {
      actions.Arm_1Action.reset().fadeIn(0.5).play();
    }

    if (actions.Arm_2Action) {
      actions.Arm_2Action.reset().fadeIn(0.5).play();
    }

    if (actions.eye2) {
      actions.eye2.reset().fadeIn(0.5).play();
    }

    // Cleanup to stop the animation when the component unmounts
    return () => {
      if (actions.FaceAction) {
        actions.FaceAction.fadeOut(0.5);
        actions.Arm_1Action.fadeOut(0.5);
        actions.Arm_2Action.fadeOut(0.5);

        actions.eye2.fadeOut(0.5);
      }
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null} rotation={[0.2, 0, 0]}>
      <group name="Scene">
        <mesh
          name="Body"
          geometry={nodes.Body.geometry}
          material={materials.Purple}
        />
        <group name="Face" position={[0, 1.6, 0.266]}>
          <mesh
            name="Sphere005"
            geometry={nodes.Sphere005.geometry}
            material={materials.Black}
          />
          <mesh
            name="Sphere005_1"
            geometry={nodes.Sphere005_1.geometry}
            material={materials.Purple}
          />
          <mesh
            name="Sphere005_2"
            geometry={nodes.Sphere005_2.geometry}
            material={materials.Blue}
          />
        </group>
        <mesh
          name="Arm_-1"
          geometry={nodes["Arm_-1"].geometry}
          material={materials.Purple}
          position={[-1.2, 0.5, 0]}
        />
        <mesh
          name="Arm_1"
          geometry={nodes.Arm_1.geometry}
          material={materials.Purple}
          position={[1.2, 0.5, 0]}
        />
        <mesh
          name="Plane004"
          geometry={nodes.Plane004.geometry}
          material={materials.Blue}
          position={[-0.001, -0.074, 0.905]}
          scale={0.851}
        />
        <mesh
          name="eye2"
          geometry={nodes.eye2.geometry}
          material={materials["Material.002"]}
          position={[0, 1.6, 0.266]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/chatgpt.glb");
